# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-02 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20171129_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcriber',
            options={'verbose_name': 'MySubcriber', 'verbose_name_plural': 'A lot of Subcribers'},
        ),
    ]
